Sign in with GitHub
goodscary/firstrubyfriend pull request #19
Opened 2023-10-22 16:05 UTC by metamoni

#### What's this PR do?
Allows users to sign in with GitHub.

##### Background context
Currently, users can only sign up/in with an email and password. This PR introduces new logic to allow them to sign up/in using their GitHub account.

The owner of the repo will have to [create an GitHub App](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app) to get a Client ID and Secret. The callback URL should be set to `<homepage_url>/auth/github/callback`. The Client ID and Secret should be stored in environment variables. To test this locally, I created a dummy app with the homepage URL set to `http://localhost:3000/`, callback url `http://localhost:3000/auth/github/callback` and pasted the Client ID and Secret straight into the `omniauth.rb` initialiser.

#### Where should the reviewer start?
1. Environment variables
For this to work, we need a way to store environment variables. I don't know how the author of this project is planning on handling these, but we could use [dotenv-rails](https://rubygems.org/gems/dotenv-rails/versions/2.1.1?locale=en).

2. Password can't be blank?
While working locally and trying to sign up with GitHub for the first time, I got a `Password can't be blank` error [while creating a new user](https://github.com/goodscary/firstrubyfriend/compare/main...metamoni:firstrubyfriend:sign-in-with-github?expand=1#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR55). I noticed that a password is not required in the `User` model, so I'm not sure where this error is coming from. To prevent this from happening, I'm [creating a secure password](https://github.com/goodscary/firstrubyfriend/compare/main...metamoni:firstrubyfriend:sign-in-with-github?expand=1#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR63) for each user that was created from omniauth. Let me know if there's a better solution here.

3. Tests
In the sessions controller tests, I had to stub out the result from the User's `from_omniauth` method. I'm not sure how big of an issue this is. Is it right for the sessions controller to have to do this or is there a better way?

4. CSS
I know the project is using tailwind CSS, but I decided to add my own styles for this button. Happy to remove these and replace them with tailwind classes if that's preferable.

#### How should this be manually tested?
1. Work on this branch locally. Remember to run `bundle` and `rails db:migrate`
2. Create a dummy [GitHub App](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app). Set the homepage URL set to `http://localhost:3000/` and the callback url to `http://localhost:3000/auth/github/callback`
3. Generate a secret, then paste the Client ID and Secret into the `omniauth.rb` file
4. Start the server with `rails s` and go to `http://localhost:3000/`, then click "Sign in with GitHub"
5. Try signing up as a new user with a random email/password
6. Test signing in/out with both users

#### Screenshots or Video

https://github.com/goodscary/firstrubyfriend/assets/22390758/e6d77d9d-ca93-4020-9aec-1fc5ef450b5b

#### Migrations
Added a `provider_uid` to users. This allows us to identify which users have signed up with a provider like GitHub (or others, if added in the future). For now I've not made this a required field, but this can be changed.

#### Additional deployment instructions
None that I can think of

#### Additional ENV Vars
This PR requires setting up the following env variables: `ENV["GITHUB_ID"]` and `ENV["GITHUB_SECRET"]`

2023-10-22 16:07 UTC, metamoni commented
@andycroll here's a PR for signing in with GitHub

2023-10-26 13:44 UTC, andycroll requested changes
Wow, thanks for your contribution. Couple of small style quibbles, but this is great.

Also work looking at what https://github.com/lazaronixon/authentication-zero does when generating OAuth as that's what we used to generate the rest of the authentication system and it'd be good to keep with that style.

2023-10-26 13:44 UTC, andycroll commented on Gemfile
> +gem "omniauth-github", github: "omniauth/omniauth-github", branch: "master"
Is there a reason to include `HEAD` from the repo rather than the released gem version?

2023-10-26 13:44 UTC, andycroll commented on app/assets/stylesheets/application.css
> +.github-button {
I _would_ prefer this to be tailwind. Cheers!

2023-10-26 13:44 UTC, andycroll commented on app/models/user.rb
> +  def self.from_omniauth(access_token)
```suggestion
  def self.from_omniauth(auth)
```

Feels a little like _`_token`_ isn't quite right here.

2023-10-26 13:44 UTC, andycroll commented on app/models/user.rb
> +  def self.set_secure_password(user)
You could set this in the method above and lose this method all together.

2023-10-26 13:44 UTC, andycroll commented on app/models/user.rb
> +    set_secure_password(user) unless user.password_digest.present?
You can [pass a block](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by) for the `_create_` version.

```suggestion
    User.find_or_create_by(email:, provider_uid:) do |user|
      user.password = SecureRandom.hex(10)
    end
```

2023-10-26 13:44 UTC, andycroll commented on test/models/user_test.rb
> +MockAccessToken = Struct.new(:user) do
Good pattern to mock this, but it's more an Auth object than a token.

2023-10-28 16:37 UTC, metamoni commented
> Also work looking at what https://github.com/lazaronixon/authentication-zero does when generating OAuth as that's what we used to generate the rest of the authentication system and it'd be good to keep with that style.

It looks like the [same gems](https://github.com/lazaronixon/authentication-zero/blob/5fb00053b000e082e2765249a8019e7a7f6e9c28/lib/generators/authentication/authentication_generator.rb#L38) are used, but there are a few differences between what they do and what I've done in this PR:
- they keep the logic in an [`omniauth_controller`](https://github.com/lazaronixon/authentication-zero/blob/5fb00053b000e082e2765249a8019e7a7f6e9c28/lib/generators/authentication/templates/controllers/html/sessions/omniauth_controller.rb.tt#L1), but I added this to the `sessions_controller`
- there's an additional [`auth/failure` path](https://github.com/lazaronixon/authentication-zero/blob/5fb00053b000e082e2765249a8019e7a7f6e9c28/lib/generators/authentication/authentication_generator.rb#L188)
- the users table has `[provider` and `uid` columns](https://github.com/lazaronixon/authentication-zero/blob/5fb00053b000e082e2765249a8019e7a7f6e9c28/lib/generators/authentication/templates/migrations/create_users_migration.rb.tt#L15), while I only added a `provider_uid`

2023-10-30 09:09 UTC, andycroll commented
I think it'd be good to standardise on using the generated code, if that's not too much bother.

2023-11-01 06:40 UTC, closed without merging