form scaffold for a mentor questionnaire
goodscary/firstrubyfriend pull request #22
Opened 2023-12-02 18:13 UTC by pratiktamang

#### What's this PR do?

Description of the high level functionality and reason for introduction of this feature.

##### Background context

Links to related Github issues
Links to related PRs
Links to errors/logs of performance data from external software

#### Where should the reviewer start?

Specific tricky bits of the code to focus on first.

#### How should this be manually tested?

If there's specific QA areas to focus on?

#### Screenshots or Video

A picture is worth a thousand words. WHy not use one?

---

#### Migrations

Broad detail of changes to the schema

#### Additional deployment instructions

Anything specific we need to worry about when this hits production, do we need to worry about releases, migrations, downtime or significant changes to UI?

#### Additional ENV Vars

Any additional configuration required in development to run this code locally, **don't include actual secret values here**.

2023-12-03 00:03 UTC, pratiktamang commented on app/models/mentor_questionnaire.rb
> +
Added inclusion as local tests wasn't letting me save this as `false`

2023-12-03 21:07 UTC, andycroll requested changes

2023-12-05 03:57 UTC, pratiktamang commented on app/models/mentor_questionnaire.rb
> +
oh wow! TIL presence is truthy. 

Removed validations and updated the test. Thanks

2023-12-07 16:42 UTC, andycroll approved these changes

2023-12-07 16:42 UTC, merged